### ISSUE TITLE
Natvrdo nastavený gecko driver

### ISSUE THREAD

**Issue by jseliga** [zdebou/liquor-exchange#21]
Gecko driver by neměl být nastavený takhle natvrdo ‒ na linuxu to rozbíjí build.

viz https://github.com/zdebou/liquor-exchange/blob/master/src/src/test/java/seleniumgluecode/test.java#L27

**Comment by jseliga** [comment]
Kdyby měl někdo podobný problém, stačí použít flag `-Dmaven.test.skip=true package`.

**Comment by lotcz** [comment]
Když build padá, je to nepříjemný, ale on by padal i kdyby ten geckodriver byl v pořádku, protože ty testy nám neprocházejí. To je správně, protože nemáme ještě implementovaný funkcionality, které se testují.

Problém tedy nevidím primárně v tom, že failují testy a padá build, jako spíš v tom, že se ten build, který by podle mě měl být produkční, používá pro vývoj.

Když se aplikace spustí příkazem **mvnw spring-boot:run**, tak to funguje - takto by se mělo vyvíjet.

Příkaz **mvnw package** slouží k vytvoření buildu pro nasazení a ten se logicky ___nesmí___ vytvořit, pokud neprojdou testy.

Vím, že jsme se bavili o tom, že se bude vyvíjet v Dockeru, ale potom by to chtělo to nějak pro vývoj připravit a mít asi dockery dva - vývoj + produkce. Používat ten flag pro vynechání testů je sice pro teď dobrý workaround, ale obecně to představuje riziko, že se do produkce dostane build, který nebyl otestován.

**Comment by divad4a** [comment]
Mělo by to být spravené v branch test-login. Už je na ní i pull request. Teď se adresa gecko driveru tahá z environment variables pod jménem "DRIVER_GECKO". Pokud nebude nastavené, bude ho hledat v kořeni aplikace (tzn. složka liquor-exchange/src).
