### ISSUE TITLE
autorizace nefunguje

### ISSUE THREAD

**Issue by lotcz** [zdebou/liquor-exchange#24]
je potřeba přidat autorizační token do všech requestů

**Comment by lotcz** [comment]
když zkouším ručně volat metodu http://localhost:8080/api/auth/changepass, která je anotována @PreAuthorize("hasRole('USER')"), tak to vrátí forbidden

**Comment by jseliga** [comment]
Jak jsem psal v dokumentaci, musí se posílat "Authorization" header.

**Comment by lotcz** [comment]
nefunguje to ani když tam ten header posílám, tobě to funguje?
